Fail builds on mac and linux of kaleido executable wasn't created

diff --git a/repos/linux_scripts/perform_kaleido_build b/repos/linux_scripts/perform_kaleido_build
--- a/repos/linux_scripts/perform_kaleido_build
+++ b/repos/linux_scripts/perform_kaleido_build
@@ -5,6 +5,11 @@ cp -r /repos/kaleido/cc/* headless/app/
 # Perform build, result will be out/Kaleido_linux_$KALEIDO_ARCH/kaleido
 ninja -C out/Kaleido_linux_$KALEIDO_ARCH -j 16 kaleido
 
+if [ ! -f "out/Kaleido_linux_$KALEIDO_ARCH/kaleido" ]
+then
+  echo "Error: Kaleido executable was not built";
+  exit 1
+fi
 
 ## First build up kaledo_minimal directory with core kaleido files
 mkdir -p /repos/build/kaleido_minimal/
diff --git a/repos/mac_scripts/build_kaleido b/repos/mac_scripts/build_kaleido
--- a/repos/mac_scripts/build_kaleido
+++ b/repos/mac_scripts/build_kaleido
@@ -58,6 +58,12 @@ cp -r ../kaleido/cc/* headless/app/
 gn gen out/Kaleido_mac_$KALEIDO_ARCH
 ninja -C out/Kaleido_mac_$KALEIDO_ARCH -j 8 kaleido
 
+if [ ! -f "out/Kaleido_mac_$KALEIDO_ARCH/kaleido" ]
+then
+  echo "Error: Kaleido executable was not built";
+  exit 1
+fi
+
 # 5) Copy build files
 mkdir -p ../build/kaleido/
 rm -r ../build/kaleido/*
